### PR TITLE
porting: use macros for log level filtering

### PR DESCRIPTION
**Pull request by xentec**
This reduces the size of the compiled binary by 7856 bytes.

### CODE REVIEW

**Comment by dhrishi** [comment]
@xentec Thanks for the contribution. We will review this PR and get back to you.

**Comment by prasad-alatkar** [comment]
LGTM

**Review by mahavirj — APPROVED** [review]

**Comment by dhrishi** [comment]
@xentec This looks great! We will get this merged.

**Comment by xentec** [comment]
Nice. Thanks!

**Comment by prasad-alatkar** [comment]
Hi @xentec the changes are included in `esp-nimble`, commit: 6d659067 . I cherry-picked your commit in my existing MR, that is why the commit SHA is changed, and I suppose that may be the reason the PR has not been marked as merged. Nevertheless your contribution is visible in commit history. Thank you for your contribution.

**Pull request closed without merging**
